import json
import sys
import re

sys.stdout.reconfigure(encoding='utf-8')

print("=========================================================================")
print(" 🚜 EXPANDING TOOLS & MACHINERY RENTAL CATALOG TO 40+ COMPREHENSIVE MACHINES")
print("=========================================================================")

EXPANDED_MACHINES = [
    # ---------------- 1. TRACTORS ----------------
    {
        "id": "mach-01",
        "name": "Mahindra 575 DI Tractor (45 HP)",
        "category": "tractors",
        "category_name": "Tractor",
        "power": "45 HP",
        "rate_hourly": 450,
        "rate_daily": 3200,
        "rate_weekly": 19000,
        "deposit": 2000,
        "rating": 4.9,
        "reviews_count": 48,
        "owner_name": "Sardar Gurdeep Singh",
        "owner_phone": "+91 98765 43210",
        "owner_whatsapp": "919876543210",
        "location": "Ludhiana Rural, Punjab",
        "lat": 30.9010,
        "lon": 75.8573,
        "distance_km": 3.2,
        "condition": "Excellent",
        "verified": 1,
        "operator_included": 1,
        "fuel_policy": "Renter pays fuel / includes 1st hour",
        "delivery_available": 1,
        "delivery_rate_per_km": 25,
        "features": "45 HP Engine, Dual Clutch, Heavy-Duty Hydraulics, Rotavator & Trolley Hook Included",
        "description": "Heavy-duty 45HP Mahindra tractor with experienced driver. Ideal for puddling, seedbed preparation, deep cultivation, and heavy trolley haulage.",
        "img": "assets/equipment/mahindra_575_tractor.png",
        "available": 1
    },
    {
        "id": "mach-02",
        "name": "John Deere 5310 4WD Multi-Crop Tractor (55 HP)",
        "category": "tractors",
        "category_name": "Tractor",
        "power": "55 HP 4WD Turbo",
        "rate_hourly": 550,
        "rate_daily": 4000,
        "rate_weekly": 24000,
        "deposit": 2500,
        "rating": 4.8,
        "reviews_count": 36,
        "owner_name": "Harpreet Singh Brar",
        "owner_phone": "+91 98123 45678",
        "owner_whatsapp": "919812345678",
        "location": "Moga Road, Punjab",
        "lat": 30.8165,
        "lon": 75.1715,
        "distance_km": 5.8,
        "condition": "Like New",
        "verified": 1,
        "operator_included": 1,
        "fuel_policy": "Includes 1st tank fuel",
        "delivery_available": 1,
        "delivery_rate_per_km": 30,
        "features": "4-Wheel Drive, Power Steering, High-Torque Turbo, Reversible MB Plough Ready",
        "description": "Premium 55HP 4WD John Deere tractor with superior traction in wet muddy soils, laser land levelling, and heavy disc harrowing.",
        "img": "assets/equipment/john_deere_tractor.png",
        "available": 1
    },
    {
        "id": "mach-03",
        "name": "Sonalika DI 745 III Rx Fuel-Saver (50 HP)",
        "category": "tractors",
        "category_name": "Tractor",
        "power": "50 HP",
        "rate_hourly": 480,
        "rate_daily": 3500,
        "rate_weekly": 21000,
        "deposit": 2000,
        "rating": 4.7,
        "reviews_count": 29,
        "owner_name": "Baldev Singh Sandhu",
        "owner_phone": "+91 98765 01234",
        "owner_whatsapp": "919876501234",
        "location": "Jalandhar Mandi, Punjab",
        "lat": 31.3260,
        "lon": 75.5762,
        "distance_km": 7.1,
        "condition": "Good",
        "verified": 1,
        "operator_included": 0,
        "fuel_policy": "Renter provides fuel",
        "delivery_available": 1,
        "delivery_rate_per_km": 20,
        "features": "High Fuel Efficiency, Oil Immersed Brakes, Easy Towing, Heavy Duty Bumper",
        "description": "Economical 50HP workhorse tractor for general farm tillage, inter-cultivation, and grain market transport.",
        "img": "assets/equipment/sonalika_tractor.png",
        "available": 1
    },
    {
        "id": "mach-04",
        "name": "Swaraj 855 FE Heavy Duty High-Torque (52 HP)",
        "category": "tractors",
        "category_name": "Tractor",
        "power": "52 HP",
        "rate_hourly": 500,
        "rate_daily": 3600,
        "rate_weekly": 22000,
        "deposit": 2000,
        "rating": 4.9,
        "reviews_count": 52,
        "owner_name": "Kulwinder Dhillon",
        "owner_phone": "+91 98555 12345",
        "owner_whatsapp": "919855512345",
        "location": "Bathinda Bypass, Punjab",
        "lat": 30.2110,
        "lon": 74.9455,
        "distance_km": 4.5,
        "condition": "Excellent",
        "verified": 1,
        "operator_included": 1,
        "fuel_policy": "Renter pays fuel",
        "delivery_available": 1,
        "delivery_rate_per_km": 25,
        "features": "Legendary 3-Cylinder High-Torque Engine, Multi-Speed PTO, Heavy Chassis",
        "description": "Farmer-favourite heavy duty tractor for hard dry soils, laser levelling, deep ripping, and high-speed cultivation.",
        "img": "assets/equipment/swaraj_tractor.png",
        "available": 1
    },
    {
        "id": "mach-05",
        "name": "New Holland 3630 TX Special Edition (55 HP)",
        "category": "tractors",
        "category_name": "Tractor",
        "power": "55 HP FPT Engine",
        "rate_hourly": 540,
        "rate_daily": 3900,
        "rate_weekly": 23500,
        "deposit": 2500,
        "rating": 4.9,
        "reviews_count": 41,
        "owner_name": "Gurcharan Singh Dhaliwal",
        "owner_phone": "+91 98144 66778",
        "owner_whatsapp": "919814466778",
        "location": "Ludhiana GT Road, Punjab",
        "lat": 30.9150,
        "lon": 75.8320,
        "distance_km": 3.8,
        "condition": "Like New",
        "verified": 1,
        "operator_included": 1,
        "fuel_policy": "Driver Included",
        "delivery_available": 1,
        "delivery_rate_per_km": 25,
        "features": "Dual Clutch, Independent PTO Clutch, Lift-O-Matic Hydraulics, ROPS Canopy",
        "description": "High performance 55HP tractor designed for continuous heavy rotavator operations, stubble management, and super seeder sowing.",
        "img": "assets/equipment/john_deere_tractor.png",
        "available": 1
    },
    {
        "id": "mach-06",
        "name": "Kubota MU4501 4WD Japanese Technology (45 HP)",
        "category": "tractors",
        "category_name": "Tractor",
        "power": "45 HP 4WD E-CDIS",
        "rate_hourly": 490,
        "rate_daily": 3500,
        "rate_weekly": 21000,
        "deposit": 2000,
        "rating": 4.9,
        "reviews_count": 38,
        "owner_name": "Kailash Chand Sharma",
        "owner_phone": "+91 94140 88990",
        "owner_whatsapp": "919414088990",
        "location": "Jaipur Agro Hub, Rajasthan",
        "lat": 26.9200,
        "lon": 75.7900,
        "distance_km": 4.1,
        "condition": "Like New",
        "verified": 1,
        "operator_included": 0,
        "fuel_policy": "Renter pays fuel",
        "delivery_available": 1,
        "delivery_rate_per_km": 20,
        "features": "Synchromesh Transmission, Bevel Gear 4WD, Ultra Low Noise, Smooth Shifting",
        "description": "Advanced Japanese 4WD tractor with superior fuel economy and tight turning radius, ideal for puddling rice fields and horticulture orchards.",
        "img": "assets/equipment/sonalika_tractor.png",
        "available": 1
    },
    {
        "id": "mach-07",
        "name": "Massey Ferguson 241 DI Maha Shakti (42 HP)",
        "category": "tractors",
        "category_name": "Tractor",
        "power": "42 HP Simpson Engine",
        "rate_hourly": 430,
        "rate_daily": 3100,
        "rate_weekly": 18500,
        "deposit": 1800,
        "rating": 4.8,
        "reviews_count": 45,
        "owner_name": "Raghunath Reddy",
        "owner_phone": "+91 98480 22334",
        "owner_whatsapp": "919848022334",
        "location": "Guntur Bypass, Andhra Pradesh",
        "lat": 16.3100,
        "lon": 80.4400,
        "distance_km": 5.0,
        "condition": "Excellent",
        "verified": 1,
        "operator_included": 1,
        "fuel_policy": "Driver Included",
        "delivery_available": 1,
        "delivery_rate_per_km": 20,
        "features": "Ultra Precision Ferguson Hydraulics, High Fuel Mileage, Rugged Simpson Engine",
        "description": "The golden standard for seedbed preparation, ridge making, groundnut inter-cultivation, and light haulage.",
        "img": "assets/equipment/mahindra_575_tractor.png",
        "available": 1
    },

    # ---------------- 2. COMBINE HARVESTERS & POST-HARVEST ----------------
    {
        "id": "mach-08",
        "name": "CLAAS CROP TIGER 30 Combine Harvester",
        "category": "harvesters",
        "category_name": "Harvester",
        "power": "76 HP Rubber Track",
        "rate_hourly": 1800,
        "rate_daily": 13500,
        "rate_weekly": 80000,
        "deposit": 5000,
        "rating": 5.0,
        "reviews_count": 64,
        "owner_name": "Jaswant Singh Virk (Virk Agro)",
        "owner_phone": "+91 98888 22334",
        "owner_whatsapp": "919888822334",
        "location": "Karnal Sector 12, Haryana",
        "lat": 29.6857,
        "lon": 76.9905,
        "distance_km": 8.4,
        "condition": "Excellent",
        "verified": 1,
        "operator_included": 1,
        "fuel_policy": "Includes 2 Expert Operators",
        "delivery_available": 1,
        "delivery_rate_per_km": 40,
        "features": "Rubber Tracks for Wet Soil, Wheat & Paddy Dual Cutter, Grain Loss < 0.8%, Clean Grain Tank",
        "description": "Self-propelled rubber-track harvester for wet paddy and wheat fields. Harvests, threshes, and cleans up to 2.2 acres per hour with zero sinking.",
        "img": "assets/equipment/claas_harvester.png",
        "available": 1
    },
    {
        "id": "mach-09",
        "name": "Preet 987 Self-Propelled Multi-Crop Harvester",
        "category": "harvesters",
        "category_name": "Harvester",
        "power": "101 HP Heavy",
        "rate_hourly": 1650,
        "rate_daily": 12000,
        "rate_weekly": 72000,
        "deposit": 5000,
        "rating": 4.8,
        "reviews_count": 33,
        "owner_name": "Gurtej Singh Sidhu",
        "owner_phone": "+91 97777 11223",
        "owner_whatsapp": "919777711223",
        "location": "Sangrur Rural, Punjab",
        "lat": 30.2458,
        "lon": 75.8421,
        "distance_km": 11.2,
        "condition": "Good",
        "verified": 1,
        "operator_included": 1,
        "fuel_policy": "Includes Certified Operator",
        "delivery_available": 1,
        "delivery_rate_per_km": 35,
        "features": "14 Ft Cutter Bar, Wheat / Mustard / Soybean / Paddy, High Unloading Auger",
        "description": "Large acreage self-propelled multi-crop combine for harvesting wheat, mustard, paddy, and soybean rapidly before seasonal rains.",
        "img": "assets/equipment/preet_harvester.png",
        "available": 1
    },
    {
        "id": "mach-10",
        "name": "Kartar 4000 Multi-Crop Heavy Combine Harvester",
        "category": "harvesters",
        "category_name": "Harvester",
        "power": "101 HP Ashok Leyland Turbo",
        "rate_hourly": 1750,
        "rate_daily": 13000,
        "rate_weekly": 78000,
        "deposit": 5000,
        "rating": 4.9,
        "reviews_count": 55,
        "owner_name": "Avtar Singh Kartar CHC",
        "owner_phone": "+91 98150 77665",
        "owner_whatsapp": "919815077665",
        "location": "Ambala Road, Haryana",
        "lat": 30.3700,
        "lon": 76.7700,
        "distance_km": 14.5,
        "condition": "Excellent",
        "verified": 1,
        "operator_included": 1,
        "fuel_policy": "2 Operators Included",
        "delivery_available": 1,
        "delivery_rate_per_km": 35,
        "features": "High Ground Clearance, Heavy Duty Drum, Air Conditioned Cabin, 2.5 Tons/hr",
        "description": "Heavy combine harvester for large fields, harvesting paddy, wheat, pulses, and oilseeds with high grain purity.",
        "img": "assets/equipment/preet_harvester.png",
        "available": 1
    },
    {
        "id": "mach-11",
        "name": "Self-Propelled Walk-Behind Crop Reaper Binder (4-Stroke)",
        "category": "harvesters",
        "category_name": "Harvester",
        "power": "10 HP Diesel",
        "rate_hourly": 320,
        "rate_daily": 2300,
        "rate_weekly": 13500,
        "deposit": 1500,
        "rating": 4.8,
        "reviews_count": 31,
        "owner_name": "Kisan Yantra Seva",
        "owner_phone": "+91 94255 33445",
        "owner_whatsapp": "919425533445",
        "location": "Indore Agri Zone, MP",
        "lat": 22.7200,
        "lon": 75.8600,
        "distance_km": 3.0,
        "condition": "Like New",
        "verified": 1,
        "operator_included": 0,
        "fuel_policy": "Renter pays fuel",
        "delivery_available": 1,
        "delivery_rate_per_km": 15,
        "features": "Cuts & Automatically Binds Crops into Bundles, 1 Acre in 1 Hour, Low Stubble Cut",
        "description": "Harvests wheat, paddy, oats, barley, and sesame and ties them into neat sheaves/bundles using biodegradable twine in a single pass.",
        "img": "assets/equipment/power_weeder.png",
        "available": 1
    },
    {
        "id": "mach-12",
        "name": "2-Row Automatic Potato Digger & Harvester",
        "category": "harvesters",
        "category_name": "Harvesters & Post-Harvest",
        "power": "Tractor 45+ HP",
        "rate_hourly": 280,
        "rate_daily": 2100,
        "rate_weekly": 12500,
        "deposit": 1200,
        "rating": 4.7,
        "reviews_count": 26,
        "owner_name": "Agrawal Potato Farms",
        "owner_phone": "+91 98370 88990",
        "owner_whatsapp": "919837088990",
        "location": "Agra Expressway Hub, UP",
        "lat": 27.1767,
        "lon": 78.0081,
        "distance_km": 5.9,
        "condition": "Good",
        "verified": 1,
        "operator_included": 0,
        "fuel_policy": "Implement only",
        "delivery_available": 1,
        "delivery_rate_per_km": 20,
        "features": "Conveyor Rubber Chain, Zero Tuber Skin Damage, Unearths 1 Acre in 1.5 Hours",
        "description": "Digs deep underneath potato ridges, separates soil through vibrating rubber conveyors, and leaves clean tubers on the soil surface for easy collection.",
        "img": "assets/equipment/potato_harvester.png",
        "available": 1
    },
    {
        "id": "mach-13",
        "name": "Groundnut Digger & Shaker Inverter",
        "category": "harvesters",
        "category_name": "Harvesters & Post-Harvest",
        "power": "Tractor 35-50 HP",
        "rate_hourly": 260,
        "rate_daily": 1900,
        "rate_weekly": 11000,
        "deposit": 1200,
        "rating": 4.8,
        "reviews_count": 24,
        "owner_name": "Jayantilal Patel",
        "owner_phone": "+91 98250 11445",
        "owner_whatsapp": "919825011445",
        "location": "Rajkot Mandi, Gujarat",
        "lat": 22.3000,
        "lon": 70.8000,
        "distance_km": 4.8,
        "condition": "Like New",
        "verified": 1,
        "operator_included": 0,
        "fuel_policy": "Implement only",
        "delivery_available": 1,
        "delivery_rate_per_km": 18,
        "features": "Digs, Shakes Dirt & Inverts Pods Upward for Sun Drying, Zero Pod Detachment",
        "description": "Specialized groundnut digger that uproots plants, gently shakes off soil from root pods, and lays them upside down in windrows for rapid field curing.",
        "img": "assets/equipment/potato_harvester.png",
        "available": 1
    },
    {
        "id": "mach-14",
        "name": "High-Capacity Multi-Crop Axial Flow Thresher",
        "category": "threshers",
        "category_name": "Threshers & Harvesters",
        "power": "Tractor PTO 35+ HP / 15 HP Motor",
        "rate_hourly": 320,
        "rate_daily": 2400,
        "rate_weekly": 14000,
        "deposit": 1500,
        "rating": 4.8,
        "reviews_count": 27,
        "owner_name": "Kishan Yantrik Kendra",
        "owner_phone": "+91 98710 77540",
        "owner_whatsapp": "919871077540",
        "location": "Rohtak Mandi, Haryana",
        "lat": 28.8955,
        "lon": 76.6066,
        "distance_km": 6.1,
        "condition": "Excellent",
        "verified": 1,
        "operator_included": 1,
        "fuel_policy": "Includes 1 Experienced Feeding Operator",
        "delivery_available": 1,
        "delivery_rate_per_km": 20,
        "features": "Wheat / Paddy / Gram / Jowar / Maize, Dual Blower Cleaning, 1.8 Tons/hr Throughput",
        "description": "Heavy stationary multi-crop thresher for clean grain recovery with zero seed breakage and fine chaff (bhusa) bagging.",
        "img": "assets/equipment/multicrop_thresher.png",
        "available": 1
    },
    {
        "id": "mach-15",
        "name": "Tractor PTO Straw Reaper (Bhusa Maker)",
        "category": "threshers",
        "category_name": "Post-Harvest & Stubble",
        "power": "Tractor PTO 50-65 HP",
        "rate_hourly": 380,
        "rate_daily": 2800,
        "rate_weekly": 16500,
        "deposit": 1800,
        "rating": 4.9,
        "reviews_count": 42,
        "owner_name": "Sukhchain Singh Brar",
        "owner_phone": "+91 98140 99001",
        "owner_whatsapp": "919814099001",
        "location": "Faridkot Road, Punjab",
        "lat": 30.6700,
        "lon": 74.7500,
        "distance_km": 6.5,
        "condition": "Excellent",
        "verified": 1,
        "operator_included": 1,
        "fuel_policy": "Driver Included",
        "delivery_available": 1,
        "delivery_rate_per_km": 25,
        "features": "Cuts Stubble & Blows Fine Wheat Straw into Trolley, Recovers Leftover Grains",
        "description": "Operates after combine harvest to cut standing stubble, crush it into high-nutrition fodder (bhusa) for cattle, and pipe it directly into a trailing trolley.",
        "img": "assets/equipment/multicrop_thresher.png",
        "available": 1
    },
    {
        "id": "mach-16",
        "name": "Square Straw Baler & Stubble Management Machine",
        "category": "balers",
        "category_name": "Harvesters & Post-Harvest",
        "power": "Tractor PTO 50-70 HP",
        "rate_hourly": 400,
        "rate_daily": 3000,
        "rate_weekly": 18000,
        "deposit": 2000,
        "rating": 4.8,
        "reviews_count": 35,
        "owner_name": "Green Fields Bio-Power Ltd",
        "owner_phone": "+91 98155 77889",
        "owner_whatsapp": "919815577889",
        "location": "Ludhiana Bypass, Punjab",
        "lat": 30.8850,
        "lon": 75.8450,
        "distance_km": 4.2,
        "condition": "Excellent",
        "verified": 1,
        "operator_included": 1,
        "fuel_policy": "Includes Operator",
        "delivery_available": 1,
        "delivery_rate_per_km": 25,
        "features": "Compacts 300 Straw Bales/hr, High-Density Twine Knotting, Easy Transport Size",
        "description": "Collects loose paddy and wheat straw from the field and compresses it into dense 20kg bales ready for sale to biomass power plants and dairy farms.",
        "img": "assets/equipment/straw_baler.png",
        "available": 1
    },
    {
        "id": "mach-17",
        "name": "Heavy-Duty High-Speed Electric Chaff Cutter (3 HP)",
        "category": "threshers",
        "category_name": "Post-Harvest & Dairy",
        "power": "3 HP Single/Three Phase Motor",
        "rate_hourly": 100,
        "rate_daily": 700,
        "rate_weekly": 4000,
        "deposit": 800,
        "rating": 4.9,
        "reviews_count": 39,
        "owner_name": "Gau-Seva Agro Implements",
        "owner_phone": "+91 98711 22334",
        "owner_whatsapp": "919871122334",
        "location": "Karnal Mandi, Haryana",
        "lat": 29.6900,
        "lon": 76.9850,
        "distance_km": 2.2,
        "condition": "Like New",
        "verified": 1,
        "operator_included": 0,
        "fuel_policy": "Electric Motor / Low Electricity Use",
        "delivery_available": 1,
        "delivery_rate_per_km": 12,
        "features": "4 Carbon Steel Blades, Reversible Gearbox, Chops 1000kg Green/Dry Fodder/hr",
        "description": "High-speed electric fodder chopper for cutting green maize, jowar, sugarcane tops, and dry straw into 15mm bite-sized cattle feed.",
        "img": "assets/equipment/power_weeder.png",
        "available": 1
    },

    # ---------------- 3. TILLAGE, ROTAVATORS, PLOUGHS & LEVELLERS ----------------
    {
        "id": "mach-18",
        "name": "Shaktiman 7-Feet Regular Smart Rotavator",
        "category": "rotavators",
        "category_name": "Rotavator",
        "power": "Tractor PTO 40-55 HP",
        "rate_hourly": 200,
        "rate_daily": 1400,
        "rate_weekly": 8400,
        "deposit": 1000,
        "rating": 4.9,
        "reviews_count": 43,
        "owner_name": "Devendra Yadav",
        "owner_phone": "+91 98260 11990",
        "owner_whatsapp": "919826011990",
        "location": "Bhopal MP Nagar, MP",
        "lat": 23.2599,
        "lon": 77.4126,
        "distance_km": 3.7,
        "condition": "Excellent",
        "verified": 1,
        "operator_included": 0,
        "fuel_policy": "Implement only (Attached to renter's tractor)",
        "delivery_available": 1,
        "delivery_rate_per_km": 15,
        "features": "48 Boron Steel L-Blades, Multi-Speed Gearbox, Heavy Trailing Board",
        "description": "Finest soil pulverizing rotavator for single-pass seedbed preparation in wheat, potato, sugarcane, and cotton fields.",
        "img": "assets/equipment/shaktiman_rotavator.png",
        "available": 1
    },
    {
        "id": "mach-19",
        "name": "Maschio Gaspardo 8-Feet Heavy Duty Rotavator (C-Blades)",
        "category": "rotavators",
        "category_name": "Rotavator",
        "power": "Tractor PTO 55-75 HP",
        "rate_hourly": 240,
        "rate_daily": 1700,
        "rate_weekly": 10200,
        "deposit": 1200,
        "rating": 5.0,
        "reviews_count": 37,
        "owner_name": "Virk Agro Custom Hiring",
        "owner_phone": "+91 98150 44332",
        "owner_whatsapp": "919815044332",
        "location": "Patiala Rural, Punjab",
        "lat": 30.3400,
        "lon": 76.3900,
        "distance_km": 5.5,
        "condition": "Like New",
        "verified": 1,
        "operator_included": 0,
        "fuel_policy": "Implement only",
        "delivery_available": 1,
        "delivery_rate_per_km": 18,
        "features": "54 C-Type Heavy Tillage Blades, Duo Cone Oil-Sealed Bearings, Side Gear Drive",
        "description": "Commercial-grade 8ft rotavator for deep residue incorporation and pulverizing hard black clayey soil.",
        "img": "assets/equipment/shaktiman_rotavator.png",
        "available": 1
    },
    {
        "id": "mach-20",
        "name": "Trimble AG-114 Laser Land Leveller (Dual Slope)",
        "category": "levellers",
        "category_name": "Leveller",
        "power": "Tractor 45-60 HP",
        "rate_hourly": 400,
        "rate_daily": 3000,
        "rate_weekly": 18000,
        "deposit": 2000,
        "rating": 4.9,
        "reviews_count": 51,
        "owner_name": "Kisan Laser Levelling Centre",
        "owner_phone": "+91 98120 77889",
        "owner_whatsapp": "919812077889",
        "location": "Kurukshetra GT Road, Haryana",
        "lat": 29.9695,
        "lon": 76.8783,
        "distance_km": 7.0,
        "condition": "Like New",
        "verified": 1,
        "operator_included": 1,
        "fuel_policy": "Includes Certified Laser Operator",
        "delivery_available": 1,
        "delivery_rate_per_km": 25,
        "features": "Precision ±2mm Laser Transmitter, Hydraulic Scraper Bucket, Saves 30% Irrigation Water",
        "description": "Grading fields with precision laser eliminates high and low spots, saving 30-40% water, improving seed germination by 25%, and increasing crop yield.",
        "img": "assets/equipment/laser_land_leveller.png",
        "available": 1
    },
    {
        "id": "mach-21",
        "name": "Lemken 2-Furrow Hydraulic Reversible MB Plough",
        "category": "ploughs",
        "category_name": "Ploughs & Cultivators",
        "power": "Tractor 45-60 HP",
        "rate_hourly": 220,
        "rate_daily": 1600,
        "rate_weekly": 9500,
        "deposit": 1000,
        "rating": 4.8,
        "reviews_count": 31,
        "owner_name": "Shivaji Patil",
        "owner_phone": "+91 98230 66778",
        "owner_whatsapp": "919823066778",
        "location": "Kolhapur Bypass, Maharashtra",
        "lat": 16.7050,
        "lon": 74.2433,
        "distance_km": 6.3,
        "condition": "Like New",
        "verified": 1,
        "operator_included": 0,
        "fuel_policy": "Implement only",
        "delivery_available": 1,
        "delivery_rate_per_km": 18,
        "features": "Hydraulic Reversible Turnover, Deep Inversion Ploughing, Hardpan Buster",
        "description": "High-grade moldboard plough for deep soil turning, burying trash/crop residue, and breaking impervious hard subsurface layers.",
        "img": "assets/equipment/reversible_mb_plough.png",
        "available": 1
    },
    {
        "id": "mach-22",
        "name": "Heavy-Duty 3-Tyne Chisel Subsoiler (Hardpan Buster)",
        "category": "ploughs",
        "category_name": "Ploughs & Cultivators",
        "power": "Tractor 55+ HP",
        "rate_hourly": 250,
        "rate_daily": 1800,
        "rate_weekly": 10800,
        "deposit": 1200,
        "rating": 4.8,
        "reviews_count": 22,
        "owner_name": "Baldev Singh Sandhu",
        "owner_phone": "+91 98765 01234",
        "owner_whatsapp": "919876501234",
        "location": "Jalandhar Mandi, Punjab",
        "lat": 31.3260,
        "lon": 75.5762,
        "distance_km": 7.1,
        "condition": "Excellent",
        "verified": 1,
        "operator_included": 0,
        "fuel_policy": "Implement only",
        "delivery_available": 1,
        "delivery_rate_per_km": 20,
        "features": "Rips Soil up to 55cm (22 Inches) Deep, Reversible Point Points, Heavy Frame",
        "description": "Shatters impenetrable hardpan layers formed by continuous shallow tillage, allowing deep crop root penetration and ground water recharge.",
        "img": "assets/equipment/reversible_mb_plough.png",
        "available": 1
    },
    {
        "id": "mach-23",
        "name": "Heavy 16-Disc Offset Trailed Hydraulic Harrow",
        "category": "cultivators",
        "category_name": "Ploughs & Cultivators",
        "power": "Tractor 45-60 HP",
        "rate_hourly": 210,
        "rate_daily": 1500,
        "rate_weekly": 9000,
        "deposit": 1000,
        "rating": 4.7,
        "reviews_count": 28,
        "owner_name": "Guru Nanak Agro Implements",
        "owner_phone": "+91 98150 99887",
        "owner_whatsapp": "919815099887",
        "location": "Ludhiana Link Road, Punjab",
        "lat": 30.9000,
        "lon": 75.8500,
        "distance_km": 3.4,
        "condition": "Good",
        "verified": 1,
        "operator_included": 0,
        "fuel_policy": "Implement only",
        "delivery_available": 1,
        "delivery_rate_per_km": 18,
        "features": "Boron Steel Notched Discs, Heavy Gang Angle Adjustment, Transport Wheels",
        "description": "Heavy disc harrow for chopping roots, clod breaking, and aerating soil after ploughing in sugarcane, cotton, and paddy fields.",
        "img": "assets/equipment/cultivator_9_tyne.png",
        "available": 1
    },
    {
        "id": "mach-24",
        "name": "Heavy-Duty 9-Tyne Spring-Loaded Cultivator",
        "category": "cultivators",
        "category_name": "Ploughs & Cultivators",
        "power": "Tractor 35-50 HP",
        "rate_hourly": 150,
        "rate_daily": 1100,
        "rate_weekly": 6500,
        "deposit": 800,
        "rating": 4.6,
        "reviews_count": 25,
        "owner_name": "Raghuvir Singh",
        "owner_phone": "+91 94140 33210",
        "owner_whatsapp": "919414033210",
        "location": "Alwar Rural, Rajasthan",
        "lat": 27.5530,
        "lon": 76.6346,
        "distance_km": 3.9,
        "condition": "Good",
        "verified": 1,
        "operator_included": 0,
        "fuel_policy": "Implement only",
        "delivery_available": 1,
        "delivery_rate_per_km": 15,
        "features": "Forged Carbon Steel Tynes, Dual Spring Shock Absorber for Stoney Soil",
        "description": "Dependable spring-loaded cultivator for rapid secondary tillage, eradicating weeds, and creating loose seedbed soil structure.",
        "img": "assets/equipment/cultivator_9_tyne.png",
        "available": 1
    },
    {
        "id": "mach-25",
        "name": "VST Shakti 130 DI Power Tiller (13 HP)",
        "category": "tillers",
        "category_name": "Power Tiller",
        "power": "13 HP Diesel",
        "rate_hourly": 220,
        "rate_daily": 1600,
        "rate_weekly": 9500,
        "deposit": 1000,
        "rating": 4.8,
        "reviews_count": 47,
        "owner_name": "Rameshwar Patel",
        "owner_phone": "+91 94250 98765",
        "owner_whatsapp": "919425098765",
        "location": "Indore Agri Market, MP",
        "lat": 22.7196,
        "lon": 75.8577,
        "distance_km": 2.5,
        "condition": "Like New",
        "verified": 1,
        "operator_included": 0,
        "fuel_policy": "Renter pays fuel",
        "delivery_available": 1,
        "delivery_rate_per_km": 15,
        "features": "Rotary Tilling & Puddling, Low Diesel Consumption (1.2 L/hr), Compact Steering",
        "description": "Compact walk-behind diesel power tiller ideal for smallholdings, orchard inter-cultivation, nursery prep, and hilly terrace farming.",
        "img": "assets/equipment/vst_power_tiller.png",
        "available": 1
    },
    {
        "id": "mach-26",
        "name": "Kirloskar Mega T 15 Deluxe Power Tiller (15 HP)",
        "category": "tillers",
        "category_name": "Power Tiller",
        "power": "15 HP High Torque",
        "rate_hourly": 250,
        "rate_daily": 1800,
        "rate_weekly": 10800,
        "deposit": 1000,
        "rating": 4.7,
        "reviews_count": 22,
        "owner_name": "Anand Shinde",
        "owner_phone": "+91 98220 33445",
        "owner_whatsapp": "919822033445",
        "location": "Nashik Agri Hub, Maharashtra",
        "lat": 19.9975,
        "lon": 73.7898,
        "distance_km": 6.0,
        "condition": "Good",
        "verified": 1,
        "operator_included": 0,
        "fuel_policy": "Renter pays fuel",
        "delivery_available": 1,
        "delivery_rate_per_km": 18,
        "features": "15 HP High Torque, Sugarcane De-Trashing Compatible, Adjustable Wheel Track",
        "description": "High-clearance power tiller specialized for sugarcane earthing-up, vineyard tilling, and vegetable bed formation.",
        "img": "assets/equipment/kirloskar_power_tiller.png",
        "available": 1
    },
    {
        "id": "mach-27",
        "name": "Mini Power Weeder 4-Stroke Petrol (Row-Crop Weeder)",
        "category": "tillers",
        "category_name": "Power Weeder",
        "power": "4-Stroke 5.5 HP Petrol",
        "rate_hourly": 120,
        "rate_daily": 800,
        "rate_weekly": 4800,
        "deposit": 800,
        "rating": 4.6,
        "reviews_count": 28,
        "owner_name": "Ravi Agriculture Equipment",
        "owner_phone": "+91 99160 44230",
        "owner_whatsapp": "919916044230",
        "location": "Ludhiana Focal Point, Punjab",
        "lat": 30.8900,
        "lon": 75.8600,
        "distance_km": 1.2,
        "condition": "Like New",
        "verified": 1,
        "operator_included": 0,
        "fuel_policy": "Renter pays petrol",
        "delivery_available": 1,
        "delivery_rate_per_km": 12,
        "features": "4-Stroke Petrol, Blade Width 300mm, Light 18kg, Inter-Row Weeding",
        "description": "Lightweight power weeder for row-crop inter-cultivation, removing weeds between vegetable rows, onion, groundnut and maize fields without crop damage.",
        "img": "assets/equipment/power_weeder.png",
        "available": 1
    },

    # ---------------- 4. SOWING, PLANTING & TRANSPLANTING ----------------
    {
        "id": "mach-28",
        "name": "Dashmesh Happy Seeder (Direct Rice Straw Sowing)",
        "category": "seeders",
        "category_name": "Seed Drills & Planters",
        "power": "Tractor PTO 50-65 HP",
        "rate_hourly": 350,
        "rate_daily": 2600,
        "rate_weekly": 15000,
        "deposit": 1500,
        "rating": 4.8,
        "reviews_count": 39,
        "owner_name": "Jaspal Singh Mann",
        "owner_phone": "+91 94178 55443",
        "owner_whatsapp": "919417855443",
        "location": "Patiala Road, Punjab",
        "lat": 30.3398,
        "lon": 76.3869,
        "distance_km": 5.2,
        "condition": "Excellent",
        "verified": 1,
        "operator_included": 0,
        "fuel_policy": "Implement only",
        "delivery_available": 1,
        "delivery_rate_per_km": 20,
        "features": "Direct Wheat Sowing into Standing Rice Stubble, Zero Stubble Burning, Moisture Preservation",
        "description": "Eco-friendly zero-tillage seed drill that cuts rice straw, deposits mulch, and sows wheat seeds in one pass, saving ₹2,500/acre in field preparation.",
        "img": "assets/equipment/happy_seeder_machine.png",
        "available": 1
    },
    {
        "id": "mach-29",
        "name": "Jagatjit All-in-One Super Seeder with Rotavator",
        "category": "seeders",
        "category_name": "Seed Drills & Planters",
        "power": "Tractor PTO 55-75 HP",
        "rate_hourly": 420,
        "rate_daily": 3100,
        "rate_weekly": 18500,
        "deposit": 2000,
        "rating": 5.0,
        "reviews_count": 48,
        "owner_name": "Amandeep Singh Sidhu",
        "owner_phone": "+91 98144 11223",
        "owner_whatsapp": "919814411223",
        "location": "Moga Rural, Punjab",
        "lat": 30.8200,
        "lon": 75.1800,
        "distance_km": 6.2,
        "condition": "Like New",
        "verified": 1,
        "operator_included": 1,
        "fuel_policy": "Includes Operator",
        "delivery_available": 1,
        "delivery_rate_per_km": 25,
        "features": "Mulches Paddy Straw & Sows Wheat Simultaneously, Precision Seed & Fertilizer Metering",
        "description": "Combines rotavator mulching and precise seed drilling in standing paddy residue without any prior burning or ploughing.",
        "img": "assets/equipment/happy_seeder_machine.png",
        "available": 1
    },
    {
        "id": "mach-30",
        "name": "Seed-cum-Fertilizer 11-Tyne Multi-Crop Drill",
        "category": "seeders",
        "category_name": "Seed Drills & Planters",
        "power": "Tractor 35+ HP",
        "rate_hourly": 180,
        "rate_daily": 1300,
        "rate_weekly": 7500,
        "deposit": 1000,
        "rating": 4.7,
        "reviews_count": 28,
        "owner_name": "Mahaveer Prasad",
        "owner_phone": "+91 98290 44321",
        "owner_whatsapp": "919829044321",
        "location": "Kota Agri Mandi, Rajasthan",
        "lat": 25.2138,
        "lon": 75.8648,
        "distance_km": 4.8,
        "condition": "Good",
        "verified": 1,
        "operator_included": 0,
        "fuel_policy": "Implement only",
        "delivery_available": 1,
        "delivery_rate_per_km": 15,
        "features": "Dual Box for Seed & Fertilizer, Adjustable Fluted Rollers, Depth Control Wheels",
        "description": "Precise mechanical seed drill for uniform spacing and depth placement of wheat, gram, mustard, maize, and soybean seeds with basal fertilizer.",
        "img": "assets/equipment/seed_cum_fertilizer_drill.png",
        "available": 1
    },
    {
        "id": "mach-31",
        "name": "Kubota 6-Row Automatic Riding Paddy Transplanter",
        "category": "seeders",
        "category_name": "Seed Drills & Planters",
        "power": "18 HP Diesel 4WD",
        "rate_hourly": 750,
        "rate_daily": 5500,
        "rate_weekly": 32000,
        "deposit": 3000,
        "rating": 5.0,
        "reviews_count": 49,
        "owner_name": "Kisan Puddling & Planting Services",
        "owner_phone": "+91 98200 44556",
        "owner_whatsapp": "919820044556",
        "location": "Karnal Rice Belt, Haryana",
        "lat": 29.6900,
        "lon": 76.9800,
        "distance_km": 7.5,
        "condition": "Like New",
        "verified": 1,
        "operator_included": 1,
        "fuel_policy": "Includes Certified Machine Driver",
        "delivery_available": 1,
        "delivery_rate_per_km": 30,
        "features": "Transplants 1 Acre in 45 Mins, Precise 6-Row Hill Spacing, Reduces Labor by 90%",
        "description": "Riding-type automatic mat nursery transplanter. Ensures uniform plant density, early tillering, and 20% higher paddy yield compared to manual labor.",
        "img": "assets/equipment/paddy_transplanter.png",
        "available": 1
    },
    {
        "id": "mach-32",
        "name": "Automatic 2-Row Potato Planter & Fertilizer Dropper",
        "category": "seeders",
        "category_name": "Seed Drills & Planters",
        "power": "Tractor 40+ HP",
        "rate_hourly": 300,
        "rate_daily": 2200,
        "rate_weekly": 13000,
        "deposit": 1500,
        "rating": 4.8,
        "reviews_count": 33,
        "owner_name": "Agrawal Potato Farms",
        "owner_phone": "+91 98370 88990",
        "owner_whatsapp": "919837088990",
        "location": "Agra Expressway Hub, UP",
        "lat": 27.1767,
        "lon": 78.0081,
        "distance_km": 5.9,
        "condition": "Excellent",
        "verified": 1,
        "operator_included": 0,
        "fuel_policy": "Implement only",
        "delivery_available": 1,
        "delivery_rate_per_km": 20,
        "features": "Cup-Chain Seed Elevator, Adjustable Ridge Maker & Fertilizer Box, Zero Seed Bruising",
        "description": "Automated planter that opens furrows, drops whole/cut seed tubers at preset distances, drops fertilizer, and forms ridges in a single trip.",
        "img": "assets/equipment/seed_cum_fertilizer_drill.png",
        "available": 1
    },
    {
        "id": "mach-33",
        "name": "Pneumatic Precision Planter (Maize, Cotton & Sunflower)",
        "category": "seeders",
        "category_name": "Seed Drills & Planters",
        "power": "Tractor 50+ HP",
        "rate_hourly": 380,
        "rate_daily": 2700,
        "rate_weekly": 16000,
        "deposit": 1800,
        "rating": 4.9,
        "reviews_count": 27,
        "owner_name": "Modern Seed Precision Tech",
        "owner_phone": "+91 98450 11990",
        "owner_whatsapp": "919845011990",
        "location": "Bellary Road, Karnataka",
        "lat": 15.1400,
        "lon": 76.9200,
        "distance_km": 6.8,
        "condition": "Like New",
        "verified": 1,
        "operator_included": 1,
        "fuel_policy": "Operator Included",
        "delivery_available": 1,
        "delivery_rate_per_km": 25,
        "features": "Vacuum Suction Seed Singulation, Zero Double Seeding, Perfect 60cm Spacing",
        "description": "High precision pneumatic vacuum seeder for hybrid seeds like maize, cotton, sunflower, and soya, ensuring 100% singulation and zero seed waste.",
        "img": "assets/equipment/seed_cum_fertilizer_drill.png",
        "available": 1
    },

    # ---------------- 5. SPRAYERS, DRONES & PLANT PROTECTION ----------------
    {
        "id": "mach-34",
        "name": "Garuda Kisan Agri Drone Pro (16L Hexacopter)",
        "category": "sprayers",
        "category_name": "Sprayers & Drones",
        "power": "Battery 16L Tank",
        "rate_hourly": 600,
        "rate_daily": 4500,
        "rate_weekly": 26000,
        "deposit": 3000,
        "rating": 4.9,
        "reviews_count": 58,
        "owner_name": "Vikram Choudhary (Kisan Drone AI)",
        "owner_phone": "+91 99887 76655",
        "owner_whatsapp": "919988776655",
        "location": "Jaipur Ring Road, Rajasthan",
        "lat": 26.9124,
        "lon": 75.7873,
        "distance_km": 4.0,
        "condition": "Like New",
        "verified": 1,
        "operator_included": 1,
        "fuel_policy": "DGCA Pilot & 4 Battery Sets Included",
        "delivery_available": 1,
        "delivery_rate_per_km": 20,
        "features": "Sprays 1 Acre in 6 Mins, Radar Terrain Following, Ultra-Fine Micron Droplets, 90% Water Savings",
        "description": "Precision agricultural drone spraying for nano-urea, pesticide, and fungicide application with zero crop trampling and maximum leaf coverage.",
        "img": "assets/equipment/garuda_kisan_drone.png",
        "available": 1
    },
    {
        "id": "mach-35",
        "name": "DJI Agras T40 Precision Spraying & Seeding Drone",
        "category": "sprayers",
        "category_name": "Sprayers & Drones",
        "power": "40L Spray / 50kg Granule",
        "rate_hourly": 950,
        "rate_daily": 7200,
        "rate_weekly": 42000,
        "deposit": 5000,
        "rating": 5.0,
        "reviews_count": 71,
        "owner_name": "Captain Rohit Verma (AeroKisan)",
        "owner_phone": "+91 98112 33445",
        "owner_whatsapp": "919811233445",
        "location": "Meerut Bypass, UP",
        "lat": 28.9845,
        "lon": 77.7064,
        "distance_km": 6.8,
        "condition": "Like New",
        "verified": 1,
        "operator_included": 1,
        "fuel_policy": "Certified Pilot + High-Speed Generator Included",
        "delivery_available": 1,
        "delivery_rate_per_km": 25,
        "features": "40L Twin Atomized Spraying, Active Phased Array Radar, 50kg Solid Fertilizer Spreader",
        "description": "Top-tier commercial agricultural drone capable of spraying up to 40 acres per day and spreading granular fertilizers/seeds across large farms.",
        "img": "assets/equipment/dji_agras_drone.png",
        "available": 1
    },
    {
        "id": "mach-36",
        "name": "Aspee 500L Tractor-Mounted Hydraulic Boom Sprayer",
        "category": "sprayers",
        "category_name": "Sprayers & Drones",
        "power": "Tractor PTO 35+ HP",
        "rate_hourly": 320,
        "rate_daily": 2300,
        "rate_weekly": 13500,
        "deposit": 1500,
        "rating": 4.8,
        "reviews_count": 36,
        "owner_name": "Punjab Agro Plant Protection",
        "owner_phone": "+91 98140 11990",
        "owner_whatsapp": "919814011990",
        "location": "Ludhiana Agro Zone, Punjab",
        "lat": 30.9100,
        "lon": 75.8400,
        "distance_km": 3.6,
        "condition": "Excellent",
        "verified": 1,
        "operator_included": 0,
        "fuel_policy": "Implement only",
        "delivery_available": 1,
        "delivery_rate_per_km": 20,
        "features": "12-Metre Hydraulic Folding Boom, 24 Ceramic Anti-Drip Nozzles, 500L Chemical Tank",
        "description": "Covers wide swath widths rapidly in wheat, mustard, cotton, and soybean crops with uniform droplet distribution.",
        "img": "assets/equipment/boom_sprayer.png",
        "available": 1
    },
    {
        "id": "mach-37",
        "name": "High-Pressure Orchard Mist Blower & Turbine Sprayer (600L)",
        "category": "sprayers",
        "category_name": "Sprayers & Drones",
        "power": "Tractor PTO 45+ HP",
        "rate_hourly": 380,
        "rate_daily": 2800,
        "rate_weekly": 16500,
        "deposit": 1800,
        "rating": 4.9,
        "reviews_count": 30,
        "owner_name": "Sahyadri Horticulture Services",
        "owner_phone": "+91 98220 55667",
        "owner_whatsapp": "919822055667",
        "location": "Nashik Grape City, Maharashtra",
        "lat": 20.0000,
        "lon": 73.7900,
        "distance_km": 5.4,
        "condition": "Like New",
        "verified": 1,
        "operator_included": 0,
        "fuel_policy": "Implement only",
        "delivery_available": 1,
        "delivery_rate_per_km": 22,
        "features": "Radial Turbine Fan, 360-Degree Canopy Penetration, Italian High-Pressure Pump",
        "description": "Specialized for orchards (grapes, mango, pomegranate, citrus, apples) to create dense fog-like mist that coats leaves from top to underside.",
        "img": "assets/equipment/boom_sprayer.png",
        "available": 1
    },
    {
        "id": "mach-38",
        "name": "Manual Knapsack Power Sprayer 16L (Battery Operated)",
        "category": "sprayers",
        "category_name": "Sprayers & Drones",
        "power": "12V 12Ah Rechargeable Battery",
        "rate_hourly": 60,
        "rate_daily": 400,
        "rate_weekly": 2200,
        "deposit": 400,
        "rating": 4.8,
        "reviews_count": 65,
        "owner_name": "Kisan Seva Kendra - Sharma Ji",
        "owner_phone": "+91 98140 33221",
        "owner_whatsapp": "919814033221",
        "location": "Ludhiana Village Centre, Punjab",
        "lat": 30.9050,
        "lon": 75.8500,
        "distance_km": 0.9,
        "condition": "Like New",
        "verified": 1,
        "operator_included": 0,
        "fuel_policy": "Includes Charger (Full Battery gives 6 hrs spray)",
        "delivery_available": 1,
        "delivery_rate_per_km": 10,
        "features": "Lightweight 5kg, Telescopic Brass Lance, Dual Speed Regulator, 4 Nozzle Attachments",
        "description": "Convenient backpack sprayer for small vegetable plots, flower beds, nursery care, and spot pesticide/herbicide application.",
        "img": "assets/equipment/knapsack_sprayer.png",
        "available": 1
    },

    # ---------------- 6. WATER PUMPS & IRRIGATION ----------------
    {
        "id": "mach-39",
        "name": "Kirloskar 7.5HP Diesel Centrifugal Water Pump",
        "category": "pumps",
        "category_name": "Water Pumps & Irrigation",
        "power": "7.5 HP Diesel",
        "rate_hourly": 160,
        "rate_daily": 1100,
        "rate_weekly": 6500,
        "deposit": 1000,
        "rating": 4.8,
        "reviews_count": 41,
        "owner_name": "Sagar Pump Centre",
        "owner_phone": "+91 97300 22110",
        "owner_whatsapp": "919730022110",
        "location": "Amravati Market, Maharashtra",
        "lat": 20.9374,
        "lon": 77.7796,
        "distance_km": 2.1,
        "condition": "Excellent",
        "verified": 1,
        "operator_included": 0,
        "fuel_policy": "Renter pays fuel",
        "delivery_available": 1,
        "delivery_rate_per_km": 15,
        "features": "1800 LPM Discharge, High Suction Lift, 100m Delivery Hose Included",
        "description": "High-discharge diesel pump set for lifting water from canals, farm ponds, rivers, and deep open wells during dry spells.",
        "img": "assets/equipment/kirloskar_diesel_pump.png",
        "available": 1
    },
    {
        "id": "mach-40",
        "name": "Honda 5HP Portable High-Pressure Irrigation Pump",
        "category": "pumps",
        "category_name": "Water Pumps & Irrigation",
        "power": "5 HP Petrol/Kerosene",
        "rate_hourly": 130,
        "rate_daily": 900,
        "rate_weekly": 5200,
        "deposit": 800,
        "rating": 4.9,
        "reviews_count": 53,
        "owner_name": "GreenField Agro Services",
        "owner_phone": "+91 98140 55667",
        "owner_whatsapp": "919814055667",
        "location": "Ludhiana GT Road, Punjab",
        "lat": 30.9120,
        "lon": 75.8340,
        "distance_km": 1.8,
        "condition": "Like New",
        "verified": 1,
        "operator_included": 0,
        "fuel_policy": "Renter pays fuel",
        "delivery_available": 1,
        "delivery_rate_per_km": 12,
        "features": "Lightweight 24kg, Self-Priming, High Pressure for Sprinkler Heads, Easy 1-Pull Start",
        "description": "Ultra-portable 5HP water pump that one farmer can carry by hand. Ideal for sprinkler setups, micro-irrigation, and horticulture plots.",
        "img": "assets/equipment/honda_petrol_pump.png",
        "available": 1
    },
    {
        "id": "mach-41",
        "name": "Mobile Solar Irrigation Trolley (5 HP DC Pump)",
        "category": "pumps",
        "category_name": "Water Pumps & Irrigation",
        "power": "5 HP Solar Array (3.5 kW)",
        "rate_hourly": 190,
        "rate_daily": 1400,
        "rate_weekly": 8200,
        "deposit": 1500,
        "rating": 4.9,
        "reviews_count": 34,
        "owner_name": "SuryaKisan Green Energy",
        "owner_phone": "+91 98450 99112",
        "owner_whatsapp": "919845099112",
        "location": "Gwalior Bypass, MP",
        "lat": 26.2183,
        "lon": 78.1828,
        "distance_km": 5.0,
        "condition": "Like New",
        "verified": 1,
        "operator_included": 0,
        "fuel_policy": "100% Free Solar Power (Zero Fuel Cost)",
        "delivery_available": 1,
        "delivery_rate_per_km": 20,
        "features": "Trolley Mounted Foldable Solar Panels, Zero Fuel / Electricity Required, Automatic MPPT Controller",
        "description": "Zero-operating-cost solar pumping trolley. Hook behind a tractor or bullock cart, fold out the panels, and pump free water all day.",
        "img": "assets/equipment/solar_irrigation_trolley.png",
        "available": 1
    },
    {
        "id": "mach-42",
        "name": "Heavy-Duty Hydraulic Tipping Farm Trolley (10-Ton)",
        "category": "tractors",
        "category_name": "Transport & Logistics",
        "power": "10 Ton Capacity Dual Axle",
        "rate_hourly": 150,
        "rate_daily": 1000,
        "rate_weekly": 6000,
        "deposit": 1000,
        "rating": 4.8,
        "reviews_count": 39,
        "owner_name": "Punjab Farm Haulage Services",
        "owner_phone": "+91 98150 22334",
        "owner_whatsapp": "919815022334",
        "location": "Ludhiana Mandi Gate 2, Punjab",
        "lat": 30.9000,
        "lon": 75.8500,
        "distance_km": 2.8,
        "condition": "Excellent",
        "verified": 1,
        "operator_included": 0,
        "fuel_policy": "Trolley Only (Hooks to any 45+ HP tractor)",
        "delivery_available": 1,
        "delivery_rate_per_km": 15,
        "features": "Heavy-Duty Telescopic Hydraulic Ram, Dual Axle 4-Tyre Suspension, 10 Ton Grain Capacity",
        "description": "Heavy hydraulic tipping trolley for grain transport to Mandi, sugarcane haulage to sugar mills, and sand/gravel manure spreading.",
        "img": "assets/equipment/cultivator_9_tyne.png",
        "available": 1
    }
]

print(f"Total catalog machines prepared: {len(EXPANDED_MACHINES)} machines across all farming categories!")

all_machines_repr = json.dumps(EXPANDED_MACHINES, indent=4)
equipment_catalog_repr = json.dumps(EXPANDED_MACHINES, indent=4)

react_machines = []
for m in EXPANDED_MACHINES:
    react_machines.append({
        "id": m["id"],
        "name": m["name"],
        "category": m["category"],
        "category_name": m["category_name"],
        "rate_hourly": m["rate_hourly"],
        "rate_daily": m["rate_daily"],
        "rating": m["rating"],
        "owner": m["owner_name"],
        "distance_km": m["distance_km"],
        "phone": m["owner_phone"],
        "whatsapp": m["owner_whatsapp"],
        "specs": m["features"].split(", "),
        "description": m["description"],
        "img": m["img"]
    })
react_catalog_repr = json.dumps(react_machines, indent=2)

# 1. Update server.py with expanded ALL_MACHINES
with open('server.py', 'r', encoding='utf-8') as f:
    server_code = f.read()

pos1 = server_code.find('ALL_MACHINES = [')
pos2 = server_code.find('def init_db()')

if pos1 != -1 and pos2 != -1:
    server_code = server_code[:pos1] + f"ALL_MACHINES = {all_machines_repr}\n\n" + server_code[pos2:]
    with open('server.py', 'w', encoding='utf-8') as f:
        f.write(server_code)
    print("[OK] Updated server.py with 42 agricultural machines")

# 2. Update app.js with expanded EQUIPMENT_CATALOG
with open('app.js', 'r', encoding='utf-8') as f:
    app_code = f.read()

pos_app1 = app_code.find('const EQUIPMENT_CATALOG = [')
pos_app2 = app_code.find('// Current Rental State')

if pos_app1 != -1 and pos_app2 != -1:
    app_code = app_code[:pos_app1] + f"const EQUIPMENT_CATALOG = {equipment_catalog_repr};\n\n" + app_code[pos_app2:]
    with open('app.js', 'w', encoding='utf-8') as f:
        f.write(app_code)
    print("[OK] Updated app.js with 42 agricultural machines")

# 3. Update React RentalsTab.jsx with expanded catalog
with open('src/components/tabs/RentalsTab.jsx', 'r', encoding='utf-8') as f:
    react_code = f.read()

pos_r1 = react_code.find('const DEFAULT_20_MACHINES = [')
pos_r2 = react_code.find('export function RentalsTab')

if pos_r1 != -1 and pos_r2 != -1:
    react_code = react_code[:pos_r1] + f"const DEFAULT_20_MACHINES = {react_catalog_repr};\n\n" + react_code[pos_r2:]
    with open('src/components/tabs/RentalsTab.jsx', 'w', encoding='utf-8') as f:
        f.write(react_code)
    print("[OK] Updated src/components/tabs/RentalsTab.jsx with 42 agricultural machines")

# 4. Re-seed SQLite database krishi_jal.db
import sqlite3
import os

if os.path.exists("krishi_jal.db"):
    os.remove("krishi_jal.db")
    print("[OK] Cleared old krishi_jal.db")

import server
server.init_db()
print("[OK] Re-seeded krishi_jal.db with 42 comprehensive agricultural machines")
